twsOrder <-
function (orderId, action = "BUY", totalQuantity = "0", orderType = "LMT", 
    lmtPrice = "0.0", auxPrice = "", tif = "", outsideRTH = "0", 
    openClose = "O", origin = .twsOrderID$CUSTOMER, ocaGroup = "", 
    account = "", orderRef = "", transmit = TRUE, parentId = "0", 
    blockOrder = "0", sweepToFill = "0", displaySize = "0", triggerMethod = "0", 
    hidden = "0", discretionaryAmt = "0", goodAfterTime = "", 
    goodTillDate = "", faGroup = "", faMethod = "", faPercentage = "", 
    faProfile = "", shortSaleSlot = "0", designatedLocation = .twsOrderID$EMPTY_STR, 
    ocaType = "0", rule80A = "", settlingFirm = "", clearingAccount = "", 
    clearingIntent = "", allOrNone = "0", minQty = "", percentOffset = "", 
    eTradeOnly = "1", firmQuoteOnly = "1", nbboPriceCap = "", 
    auctionStrategy = "0", startingPrice = "", stockRefPrice = "", 
    delta = "", stockRangeLower = "", stockRangeUpper = "", overridePercentageConstraints = "0", 
    volatility = "", volatilityType = "", deltaNeutralOrderType = "", 
    deltaNeutralAuxPrice = "", continuousUpdate = "0", referencePriceType = "", 
    trailStopPrice = "", basisPoints = "", basisPointsType = "", 
    scaleInitLevelSize = "", scaleSubsLevelSize = "", scalePriceIncrement = "", 
    notHeld = FALSE, algoStrategy = "", algoParams = NULL, whatIf = FALSE, 
    clientId = "", permId = "", exemptCode = "-1", hedgeType = "", 
    hedgeParam = "", optOutSmartRouting = FALSE, scaleTable = "", 
    activeStartTime = "", activeStopTime = "", trailingPercent = "", 
    deltaNeutralConId = "0", deltaNeutralSettlingFirm = "", deltaNeutralClearingAccount = "", 
    deltaNeutralClearingIntent = "", deltaNeutralOpenClose = "", 
    deltaNeutralShortSale = "0", deltaNeutralShortSaleSlot = "0", 
    deltaNeutralDesignatedLocation = "", scalePriceAdjustValue = "0", 
    scalePriceAdjustInterval = "0", scaleProfitOffset = "0", 
    scaleAutoReset = "0", scaleInitPosition = "0", scaleInitFillQty = "0", 
    scaleRandomPercent = "0", smartComboRoutingParams = NULL, 
    smartComboRoutingParamsCount = "0", orderComboLegs = NULL, 
    orderComboLegsCount = "0", comboLegs = NULL, comboLegsCount = "0", 
    orderMiscOptions = NULL) 
{
    if (missing(orderId)) 
        orderId <- ""
    structure(list(orderId = orderId, clientId = clientId, permId = permId, 
        action = action, totalQuantity = as.character(as.numeric(totalQuantity)), 
        orderType = orderType, lmtPrice = as.character(lmtPrice), 
        auxPrice = as.character(auxPrice), tif = tif, ocaGroup = ocaGroup, 
        ocaType = ocaType, orderRef = orderRef, transmit = as.character(as.integer(transmit)), 
        parentId = parentId, blockOrder = blockOrder, sweepToFill = sweepToFill, 
        displaySize = displaySize, triggerMethod = triggerMethod, 
        outsideRTH = outsideRTH, hidden = hidden, goodAfterTime = goodAfterTime, 
        goodTillDate = goodTillDate, overridePercentageConstraints = overridePercentageConstraints, 
        rule80A = rule80A, allOrNone = allOrNone, minQty = minQty, 
        percentOffset = percentOffset, trailStopPrice = trailStopPrice, 
        faGroup = faGroup, faProfile = faProfile, faMethod = faMethod, 
        faPercentage = faPercentage, openClose = openClose, origin = origin, 
        shortSaleSlot = shortSaleSlot, designatedLocation = designatedLocation, 
        discretionaryAmt = discretionaryAmt, eTradeOnly = eTradeOnly, 
        firmQuoteOnly = firmQuoteOnly, nbboPriceCap = nbboPriceCap, 
        auctionStrategy = auctionStrategy, startingPrice = startingPrice, 
        stockRefPrice = stockRefPrice, delta = delta, stockRangeLower = stockRangeLower, 
        stockRangeUpper = stockRangeUpper, volatility = volatility, 
        volatilityType = volatilityType, continuousUpdate = continuousUpdate, 
        referencePriceType = referencePriceType, deltaNeutralOrderType = deltaNeutralOrderType, 
        deltaNeutralAuxPrice = deltaNeutralAuxPrice, basisPoints = basisPoints, 
        basisPointsType = basisPointsType, scaleInitLevelSize = scaleInitLevelSize, 
        scaleSubsLevelSize = scaleSubsLevelSize, scalePriceIncrement = scalePriceIncrement, 
        account = account, settlingFirm = settlingFirm, clearingAccount = clearingAccount, 
        clearingIntent = clearingIntent, algoStrategy = algoStrategy, 
        algoParams = algoParams, whatIf = as.character(as.integer(whatIf)), 
        notHeld = as.character(as.integer(notHeld)), exemptCode = as.character(as.integer(exemptCode)), 
        hedgeType = hedgeType, hedgeParam = hedgeParam, optOutSmartRouting = as.character(as.integer(optOutSmartRouting)), 
        scaleTable = scaleTable, activeStartTime = activeStartTime, 
        activeStopTime = activeStopTime, trailingPercent = trailingPercent, 
        deltaNeutralConId = deltaNeutralConId, deltaNeutralSettlingFirm = deltaNeutralSettlingFirm, 
        deltaNeutralClearingAccount = deltaNeutralClearingAccount, 
        deltaNeutralClearingIntent = deltaNeutralClearingIntent, 
        deltaNeutralOpenClose = deltaNeutralOpenClose, deltaNeutralShortSale = deltaNeutralShortSale, 
        deltaNeutralShortSaleSlot = deltaNeutralShortSaleSlot, 
        deltaNeutralDesignatedLocation = deltaNeutralDesignatedLocation, 
        scalePriceAdjustValue = scalePriceAdjustValue, scalePriceAdjustInterval = scalePriceAdjustInterval, 
        scaleProfitOffset = scaleProfitOffset, scaleAutoReset = scaleAutoReset, 
        scaleInitPosition = scaleInitPosition, scaleInitFillQty = scaleInitFillQty, 
        scaleRandomPercent = scaleRandomPercent, smartComboRoutingParams = smartComboRoutingParams, 
        smartComboRoutingParamsCount = smartComboRoutingParamsCount, 
        orderComboLegs = orderComboLegs, orderComboLegsCount = orderComboLegsCount, 
        comboLegs = comboLegs, comboLegsCount = comboLegsCount, 
        orderMiscOptions = orderMiscOptions), class = "twsOrder")
}
